CREATE DATABASE CDB1
 USER SYS IDENTIFIED BY SYS
 USER SYSTEM IDENTIFIED BY MANAGER
 LOGFILE GROUP 1 ('/oradata/CDB1/redo_11.dbf','/oradata/CDB1/redo_12.dbf') 
 SIZE 100M BLOCKSIZE 512,
 GROUP 2 ('/oradata/CDB1/redo_21.dbf','/oradata/CDB1/redo_22.dbf') 
 SIZE 100M BLOCKSIZE 512,
 GROUP 3 ('/oradata/CDB1/redo_31.dbf','/oradata/CDB1/redo_32.dbf') 
 SIZE 100M BLOCKSIZE 512
 MAXLOGHISTORY 1
 MAXLOGFILES 16
 MAXLOGMEMBERS 3
 MAXDATAFILES 1024
 CONTROLFILE REUSE
 CHARACTER SET WE8ISO8859P15
 NATIONAL CHARACTER SET AL16UTF16
 EXTENT MANAGEMENT LOCAL
 DATAFILE '/oradata/CDB1/system_01.dbf' 
 SIZE 700M REUSE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED
 SYSAUX DATAFILE '/oradata/CDB1/sysaux_01.dbf' 
 SIZE 550M REUSE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED
 DEFAULT TABLESPACE USERS
 DATAFILE '/oradata/CDB1/users_01.dbf' 
 SIZE 500M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED
 DEFAULT TEMPORARY TABLESPACE TEMP
 TEMPFILE '/oradata/CDB1/temp_01.dbf' 
 SIZE 20M REUSE AUTOEXTEND ON NEXT 640K MAXSIZE UNLIMITED
 UNDO TABLESPACE UNDO
 DATAFILE '/oradata/CDB1/undo_01.dbf' 
 SIZE 200M REUSE AUTOEXTEND ON NEXT 5120K MAXSIZE UNLIMITED
 ENABLE PLUGGABLE DATABASE
 SEED
 FILE_NAME_CONVERT = ('/oradata/CDB1/', '/oradata/CDB1/pdbseed/')
 SYSTEM DATAFILES SIZE 125M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
 SYSAUX DATAFILES SIZE 100M
;
